# Generated by Django 5.1.4 on 2025-01-13 23:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('summarisation', '0002_uploadedfile_delete_pdffile'),
    ]

    operations = [
        migrations.AlterField(
            model_name='uploadedfile',
            name='file',
            field=models.FileField(upload_to='uploads'),
        ),
    ]
