# Generated by Django 5.1.4 on 2025-01-14 00:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('summarisation', '0003_alter_uploadedfile_file'),
    ]

    operations = [
        migrations.AlterField(
            model_name='uploadedfile',
            name='file',
            field=models.FileField(upload_to='uploads/'),
        ),
    ]
