# Generated by Django 5.1.4 on 2025-06-20 16:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('customers', '0002_customer_first_name_customer_last_name'),
    ]

    operations = [
        migrations.RenameField(
            model_name='customer',
            old_name='paystack_id',
            new_name='paystack_id',
        ),
    ]
