# Generated by Django 5.1.4 on 2025-06-26 21:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('customers', '0003_rename_stripe_id_customer_paystack_id'),
    ]

    operations = [
        migrations.RenameField(
            model_name='customer',
            old_name='paystack_id',
            new_name='customer_id',
        ),
    ]
