# Generated by Django 5.1.4 on 2025-06-26 21:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('customers', '0004_rename_paystack_id_customer_customer_id'),
    ]

    operations = [
        migrations.RenameField(
            model_name='customer',
            old_name='customer_id',
            new_name='paystack_id',
        ),
    ]
