# Generated by Django 5.1.4 on 2025-02-11 00:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('subscriptions', '0002_alter_subscriptionprice_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='subscriptionprice',
            name='trial_period_days',
            field=models.IntegerField(default=7, help_text='Number of days for the free trial'),
        ),
        migrations.AddField(
            model_name='usersubscription',
            name='trial_used',
            field=models.BooleanField(default=False),
        ),
    ]
