# Generated by Django 5.1.4 on 2025-02-11 00:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('subscriptions', '0003_subscriptionprice_trial_period_days_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='subscriptionprice',
            name='trial_period_days',
        ),
        migrations.RemoveField(
            model_name='usersubscription',
            name='trial_used',
        ),
    ]
