# Generated by Django 5.1.4 on 2025-02-11 20:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        ('subscriptions', '0006_delete_myuser'),
    ]

    operations = [
        migrations.AddField(
            model_name='subscriptionprice',
            name='groups',
            field=models.ManyToManyField(blank=True, to='auth.group'),
        ),
    ]
