# Generated by Django 5.1.4 on 2025-02-11 20:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('subscriptions', '0007_subscriptionprice_groups'),
    ]

    operations = [
        migrations.AddField(
            model_name='subscriptionprice',
            name='active',
            field=models.BooleanField(default=True),
        ),
    ]
