# Generated by Django 5.1.4 on 2025-06-20 21:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('subscriptions', '0009_rename_paystack_id_subscriptionprice_paystack_i'),
    ]

    operations = [
        migrations.RenameField(
            model_name='subscriptionprice',
            old_name='paystack_i',
            new_name='paystack_id',
        ),
    ]
