# Generated by Django 5.1.4 on 2025-06-20 21:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('subscriptions', '0010_rename_paystack_i_subscriptionprice_paystack_id'),
    ]

    operations = [
        migrations.RenameField(
            model_name='subscriptionprice',
            old_name='paystack_id',
            new_name='stripe_id',
        ),
    ]
