# Generated by Django 5.1.4 on 2025-06-23 16:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('subscriptions', '0013_usersubscription_stripe_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='usersubscription',
            name='stripe_id',
        ),
    ]
