# Generated by Django 5.1.4 on 2025-06-23 19:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('subscriptions', '0014_remove_usersubscription_stripe_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subscriptionprice',
            name='interval',
            field=models.CharField(choices=[('month', 'Monthly'), ('year', 'Annually')], default='month', max_length=120),
        ),
    ]
