# Generated by Django 5.1.4 on 2025-06-24 20:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('subscriptions', '0015_alter_subscriptionprice_interval'),
    ]

    operations = [
        migrations.AddField(
            model_name='usersubscription',
            name='subscription_code',
            field=models.CharField(blank=True, max_length=120, null=True),
        ),
    ]
