# Generated by Django 5.1.4 on 2025-06-24 21:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('subscriptions', '0016_usersubscription_subscription_code'),
    ]

    operations = [
        migrations.AddField(
            model_name='usersubscription',
            name='customer_code',
            field=models.CharField(blank=True, max_length=120, null=True),
        ),
    ]
