# Generated by Django 5.1.4 on 2025-06-26 12:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('subscriptions', '0017_usersubscription_customer_code'),
    ]

    operations = [
        migrations.AddField(
            model_name='usersubscription',
            name='last_payment_reference',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
