# Generated by Django 5.1.4 on 2025-06-26 21:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('subscriptions', '0019_paystacktransaction'),
    ]

    operations = [
        migrations.DeleteModel(
            name='PaystackTransaction',
        ),
    ]
