# Generated by Django 5.1.4 on 2025-03-25 20:47

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('spreadsheet', '0002_uploadedspreadsheet_user'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='uploadedspreadsheet',
            options={'ordering': ['-uploaded_at']},
        ),
        migrations.AddField(
            model_name='uploadedspreadsheet',
            name='file_size',
            field=models.BigIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='uploadedspreadsheet',
            name='file_type',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='uploadedspreadsheet',
            name='original_filename',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddIndex(
            model_name='uploadedspreadsheet',
            index=models.Index(fields=['user', 'uploaded_at'], name='spreadsheet_user_id_d1cfe1_idx'),
        ),
        migrations.AddIndex(
            model_name='uploadedspreadsheet',
            index=models.Index(fields=['uploaded_at'], name='spreadsheet_uploade_07fe1a_idx'),
        ),
    ]
