# Generated by Django 5.1.4 on 2025-03-25 20:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('spreadsheet', '0003_alter_uploadedspreadsheet_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='uploadedspreadsheet',
            options={},
        ),
        migrations.RemoveIndex(
            model_name='uploadedspreadsheet',
            name='spreadsheet_user_id_d1cfe1_idx',
        ),
        migrations.RemoveIndex(
            model_name='uploadedspreadsheet',
            name='spreadsheet_uploade_07fe1a_idx',
        ),
        migrations.RemoveField(
            model_name='uploadedspreadsheet',
            name='file_size',
        ),
        migrations.RemoveField(
            model_name='uploadedspreadsheet',
            name='file_type',
        ),
        migrations.RemoveField(
            model_name='uploadedspreadsheet',
            name='original_filename',
        ),
    ]
